name: UI testing

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Start dev server
        run: npm run dev > /dev/null 2>&1 &
      - name: Run tests
        run: npm run test