name: Publish to preprod

on:
  push:
    branches: ["*"]

jobs:
  deploy:
    name: Deploy the website in preproduction
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/setup-action@v1.3.4
      with:
        jvm: adoptium:1.17.0.7
        apps: sbt
    - name: Build static website
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 1
        command: |
          sbt "compile; fullLinkJS; publicFolderProd"
          npm install
          npx sass src/main/resources/css/main.scss src/main/resources/css/output.scss
          npm run build
