name: Publish to preprod

on:
  push:
    branches: ["*"]

jobs:
  deploy:
    name: Deploy the website in preproduction
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/setup-action@v1.3.4
      with:
        jvm: adoptium:1.17.0.7
        apps: sbt
    - name: Build static website
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 1
        command: sbt "compile; fullLinkJS; publicFolderProd"
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        ## limits ssh access and adds the ssh public keys of the listed GitHub users
        wait-timeout-minutes: 10
    - name: Build static website
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: |
          npm install
          npx sass src/main/resources/css/main.scss src/main/resources/css/output.scss
          npm run build
