name: Push to Clever Cloud

on:
  workflow_call:
    secrets:
      CLEVER_TOKEN:
        required: true
      CLEVER_SECRET:
        required: true
      CLEVER_APP_ID:
        required: true

jobs:
  push-cc:
    name: Deploy to Clever Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          npm install -g clever-tools 
          clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
          clever link ${{ secrets.CLEVER_APP_ID}}
          clever deploy --force